apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "simple-kubernetes-webhook.acme.com"
webhooks:
  - name: "simple-kubernetes-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: simple-kubernetes-webhook
        path: /validate-pods
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQXRDZ0F3SUJBZ0lRRHVGTlRNS28wZXk0QWpqclJqcGZBekFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TWpBMU1EUXdNVEE0TVRWYUdBOHlNRFV5TURVd05EQXhNVGd4TlZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURXCldRbUV5NlNFNGtUWGVIa2M4MWJ3T0dUdzVKREhFdUx4YjJmbmxWUzQzazNDN3NtZWlWc2REY1NNRnh2SDEyQkwKQjJMY0Y1MDJrck5GWG5acGdyaGtMQTZtWFpSUmp4N2RyanMrVFgrYnhLczFZbWR6QWdsM3lMSnVGRlh3MDZJNQoxY2ljL045aFgyNHBaeHhYWFBmUkZsWVFxZks2eDkyam5JN1M3RlJyRUltRlNVbnNwd2RPSkZhNG9XNE80Q2phCnJRVmJBeUxHYXlRdm54NzVYaGsyYzY1S1kvektIemhVUVJwK0dEc2RZUXhBZVJOZURLVys0RmRGK05OdUhGMEkKaUxYcHA3SzZtc0JFT3NZckpCUDB5OU1oTzlOY2FzVHQxc1ZiNy96OXNxblZuVWgzQlVJeDFkREd3cHJaalVDUgpJenZGMy9rL1Q0ajhCSGlsb0cvTlp1MU1qU0U1S3NKUVY3ZWN3OWUxRm0zaWZaSmZHRTNMbjBwbFBoVjQvY1dMCk1lUFlvQ1BDZlZ2c3BGMEpjRFFwbWFiK29mUXRocmZrT3VUVUtZUVlobk1BQnVWUmRUa0MxR2thcm91TkpkSVMKdlBRUUd3NTdvQkM5SHphNzhERlhFT3NhTXVabUJPR1lUOFVwUUdoYzUycEtkOWxWTzRjLzJhK2FFZGVBUDltNwppQ1I3VkxNaFVDV0NDNU9WQzBDRzY1Y1BXbitleWFONXJqWmJNRlA5cWZua2xYV2wrNGtaT3piVTRVbFFIOWN6CnRTZmhMQU9iU3dINU9DdTRkdmI2K2pBZlNJUUEwcTllN0Ivd0R1ODZjSVIyYVpwSGZVQ0VTanVQVFVJdjkzUTAKa3BwS3JUQVJ1aENpRTlVR25rb0xNL2cydGNkQ0FvMHlJM2hMSE8va2pRSURBUUFCbzBJd1FEQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVmallHRGJPK1NkZ2FzYTIyCnhIOEJWNFphR29Zd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFLWjh2TUh1NGk4ajhwVlB6ZXBUTDk5WTcraTgKbnY1WXNCRS9QNmlZVytxNmEwR3RQclJDdjNZM055NmFRQnNvTHd6eUZtQkZyNHNLWjlFdFREbjRCa25kVGxBdwo4WWZaaGlvU25YN2dFdnJubEVvVEZ6Y0dPc2V5QU9qOUk3dS9qRGNyWi80Z0ZnVE1WamJnS3Z5dFJOWDQ1YVhwClUrYkg2dU1jaUJBbkZia3RReU5TNld1c0g5ODJmeFRpcjN4ai9yUVFobUdHVWJEYmNSbUQ5NjlWTTZKdHdDZUcKVVRML0puMk9Gd2MwMHVML2NPOFBtamhNdUJZWWZuS3FUd1VWa1BQQmJ1M2VkNUJGKzhENXNWU0RVMytRbUZ3ZwpKbEdBb2h0Q0tGb1BFaFd4ZDVQN2FBNE1aMzJIUjl1VHdlQmtVTmJxSVU4TEEzUjJoMlB6a2c4Q1NlaWRxWjZKCk96M0JyOEtlTE1UNWRTSTZ6WDByL2p6UVAwTXFFd2orK1BybW1obzdJaWF4N0hlSld4UjZ4bnk2S2pwRG4xUlgKL1FXUnBjUDJLOVRsbVNoQUFKRkRrQjNlN3V5dEtaRE1ETEcrc250ZVgwMG5pT3Z1dkk3amhHSFhLYmlrK0E3bQpuSnZiT0NlSEdTS05kMlVqdEM4bW5NdU1ucWhicFNmdW1OaHkrMzB6bnhxSkloMG52MXdvc040Wjl6TGMyYktyCm1JZGNMVS8rd2w2OFVUdnJBb0NDV2lBbEM1VmVvUWdEOTY0VTg0VS8zVnJSSWdEYlZnZDViRUU1dElyeDNYcjAKMG9HQlNIZVY2VGZvcVNmU09rN3JYUWpSNkc2bkZiNmZ1WGdqR0IvSmd5RXpWY1RVQjl1djIvK2hFdW9vcFNjcApLdjhzbjdDUGxuYlNxQ2RCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
